version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.32
    - 14.14.34
    - 14.14.41
    - 15.0.0
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.19
    - 6.1.20
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: jest-localstorage-mock
    versions:
    - 2.4.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.15
    - 7.13.8
  - dependency-name: next-pwa
    versions:
    - 5.2.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.2
    - 4.17.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.15
    - 6.1.19
    - 6.1.20
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
  - dependency-name: styled-icons
    versions:
    - 10.30.0
    - 10.32.0
  - dependency-name: faker
    versions:
    - 5.3.1
    - 5.5.2
  - dependency-name: "@types/faker"
    versions:
    - 5.5.0
  - dependency-name: git-commit-msg-linter
    versions:
    - 3.0.4
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.2
    - 4.17.0
    - 4.18.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
    - 5.1.8
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
  - dependency-name: react-use
    versions:
    - 17.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
